DROP DATABASE IF EXISTS moviesMVP;

CREATE DATABASE moviesMVP;

USE moviesMVP;

CREATE TABLE favorites (
  id INT(20) NOT NULL,
  title VARCHAR(50) NOT NULL,
  poster VARCHAR(100),
  description VARCHAR(255) NOT NULL,
  vote INT(20) NOT NULL,
  PRIMARY KEY(id)
);